OnlineTestApplication/OnlineTestApplication/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('teacher/',include('teacher.urls')),
    path('student/',include('student.urls')),
    path('onlinetest/',include('onlinetest.urls')),
     path('password_change/', views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
         path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

OnlineTestApplication/main/urls.py
from django.urls import path
from .views import *
app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('signup/<str:category>/', signup, name='signup'),
    path('teachersignin/',teacher_signin,name='teacher_signin'),
    path('studentsignin/',student_signin,name='student_signin'),
    path('signout/', signout, name='signout'),

]

OnlineTestApplication/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    is_verified = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)

OnlineTestApplication/main/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class SignupForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your First Name'}),label='First Name')
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your Last Name'}),label='Last Name')
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your Email', 'type': 'email'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter User Name'}),label='User Name')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Enter New Password'}),label='New Password')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Enter Confrim Password'}),label='Confirm Password')
   
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email',
                  'username', 'password1', 'password2']

OnlineTestApplication/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import SignupForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from teacher.models import *
from student.models import *
from .models import User

# Create your views here.
def home(request):
    return render(request, 'main/base.html')


def signup(request, category):
    if request.user.is_authenticated:
        if user.is_teacher:
            return redirect('teacher:profile')
        else:
            return redirect('student:profile')
    form = SignupForm()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            if category == 'teacher':
                form.is_teacher = True
                form.save()
                Teacher.objects.create(user=form)
                return redirect('main:teacher_signin')
            else:
                form.is_student = True
                form.save()
                Student.objects.create(user=form)
                return redirect('main:student_signin')
            # messages.success(request, "User Saved Successfully")
            # form = SignupForm()
        else:
            messages.error(request, "Please Provide valid data")

    return render(request, 'main/signup.html', locals())


def teacher_signin(request):
    if request.method == 'POST':
        data = request.POST
        username = data['username']
        password = data['pass']
        user = authenticate(username=username, password=password)
        if user and user.is_verified and user.is_teacher:
            login(request, user)
            messages.success(request, f"Welcome, {username}")
            return redirect('teacher:profile')
        else:
            messages.error(request, 'Please Provide Valid Username / Password')
    if request.user.is_authenticated and request.user.is_verified and request.user.is_teacher:
        return redirect('teacher:profile')
    return render(request, 'main/teacher_signin.html')


def student_signin(request):
    if request.method == 'POST':
        data = request.POST
        username = data['username']
        password = data['pass']
        user = authenticate(username=username, password=password)
        if user and user.is_verified and user.is_student:
            login(request, user)
            messages.success(request, f"Welcome, {username}")
            return redirect('student:profile')
        else:
            messages.error(request, 'Please Provide Valid Username / Password')
        if request.user.is_authenticated and request.user.is_verified and request.user.is_student:
            return redirect('student:profile')
    return render(request, 'main/student_signin.html')

def signout(request):
    request.session.flush()
    logout(request)
    return redirect('main:home')

OnlineTestApplication/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Online Test{% endblock title %}</title>
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
     integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block css %}
      <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    {% endblock css %}
    
      
</head>

<body>
    
    <header class="header">
        <div class="navbar-area">
            <nav class="navbar">
                <ul>
                    <li><a href="{% url 'main:home' %}"><i class="fa fa-home"></i> Home</a</li>
                    <li><a href="{% url 'main:teacher_signin' %}"><i class="fas fa-chalkboard-teacher"></i> &nbsp;Teacher</a></li>
                    <li><a href="{% url 'main:student_signin' %}"><i class="fas fa-user-graduate"></i> &nbsp;Student</a></li>
                 </ul>
            </nav>
        </div>
    </header>

    {% block content1 %} 

    {% endblock %}
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-auto-replace-svg="nest"></script>
</body>
</html>

OnlineTestApplication/templates/main/signup.html
{% extends 'main/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Signup{% endblock title %}

{% block css %}
{{block.super}}
<link rel="stylesheet" href="{% static 'main/css/signup.css' %}">
{% endblock css %}



{% block content1 %}  
  
    <center>
    <div>
        <h1 class="createuser">SIGNUP</h1>
    </div>
    <div style=" width: 50%; border: 10px outset rgb(28, 176, 196); border-radius: 60px;">
    
        
    <div style="background: linear-gradient(to bottom, #ccffff 0%, #5f98ee 100%);  border-radius: 50px;">
        <br>
        <form method="POST"  style="text-align: center;">
            <!-- {% if form.errors %}
            <div class="alert alert-error">
                <h4>Please fix the following errors</h4>
                <ul>
                    {% for field in form %}
                    {% if field.errors %}
                    {% for error in field.errors %}
                    <p><strong>{{ field.name }}</strong> {{ error|escape }}</p>
                    {% endfor %}
                    {% endif %}
                    {% endfor %}
                </ul>
                {% if form.non_field_errors %}
                {{ form.non_field_errors }}
                {% endif %}
            </div>
            {% endif %} -->
            
        {% csrf_token %}
     
            {{form.first_name|as_crispy_field}}<br>
        
            {{form.last_name|as_crispy_field}}<br>

            {{form.email|as_crispy_field}}<br>
       
            {{form.username|as_crispy_field}}<br>
       
            {{form.password1|as_crispy_field}}<i class="fas fa-info-circle"></i><br><br>
            
            {{form.password2|as_crispy_field}}<br>
    
            <br><center><button type='sumbit' class="btn">CONFIRM</button></center>
            <br><br>
        </form>
    </div>
    </div>
</center> 

{% endblock %}

OnlineTestApplication/templates/main/student_signin.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Student | Signin{% endblock title %}

{% block css %}
{{block.super}}
<link rel="stylesheet" href="{% static 'main/css/signup.css' %}">
{% endblock css %}

{% block content1 %}  
  
    <center>
    <div>
        <h1 style="font-size: 60px; color: whitesmoke;">Student SignIn</h1>
    </div>
    <br>
    <div style=" width: 40%; border: 10px outset rgb(28, 176, 196); border-radius: 60px;">
    
        
    <div style="background: linear-gradient(to bottom, #ccffff 0%, #5f98ee 100%);  border-radius: 50px;">
        <br>
        <form method="POST"  style="text-align: center;">           
       
            {% csrf_token %}
            <label for='username' style="font-size: 13pt; font-weight: bold;">Username :</label>
            <input name='username' class="form-control" type='text' placeholder="Enter Username" required style="border: 2px outset rgb(28, 176, 196);">
            <br>
            <label for='pass'  style="font-size: 13pt; font-weight: bold;">Password : </label>
            <input name='pass' class="form-control" type='password'placeholder="Enter Password" required style="border: 2px outset rgb(28, 176, 196);">
            <a href="{% url 'password_reset' %}" style=" font-size: 10pt; color: blue; text-decoration: underline; float: right;"> Forgot password ?</a>

            <br>
    
            <br><center><button type='sumbit' class="btn">CONFIRM</button></center>
            
            <br><br>
        </form>

    </div>
    
        <!-- <button class="btn"><i class="fas fa-chalkboard-teacher"></i> &nbsp;Create an Account</button></a>&nbsp;&nbsp; -->
    </div>
    <br>
    <p style="font-size: 10pt; font-weight: 600;">For New User</p>
    <hr>
        <a href="{% url 'main:signup' 'student' %}">
        <button type='sumbit' style="background-color: rgb(8, 128, 8); border-radius: 5px; color: white"><i class="fas fa-user-plus"></i> Create an Account</button></a>
    
       
</center> 

{% endblock %}

OnlineTestApplication/templates/main/teacher_signin.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Teacher | Signin{% endblock title %}

{% block css %}
{{block.super}}
<link rel="stylesheet" href="{% static 'main/css/signup.css' %}">
{% endblock css %}



{% block content1 %}  
  
    <center>
    <div>
        <h1 style="font-size: 60px; color: whitesmoke;">Teacher SignIn</h1>
    </div>
    <br>
    <div style=" width: 40%; border: 10px outset rgb(28, 176, 196); border-radius: 60px;">
    
        
    <div style="background: linear-gradient(to bottom, #ccffff 0%, #5f98ee 100%);  border-radius: 50px;">
        <br>
        <form method="POST"  style="text-align: center;">  
       
            {% csrf_token %}
            <label for='username' style="font-size: 13pt; font-weight: bold;">Username :</label>
            <input name='username' class="form-control" type='text' placeholder="Enter Username" required style="border: 2px outset rgb(28, 176, 196);">
            <br>
            <label for='pass'  style="font-size: 13pt; font-weight: bold;">Password : </label>
            <input name='pass' class="form-control" type='password'placeholder="Enter Password" required style="border: 2px outset rgb(28, 176, 196);">
            <a href="{% url 'password_reset' %}" style=" font-size: 10pt; color: blue; text-decoration: underline; float: right;"> Forgot password ?</a>

            <br>
    
            <!-- <br><center><button type='sumbit' style="background-color:rgb(5, 82, 117); width: 30%; border-radius: 10px; color: white">CONFIRM</button></center> -->
            <br><center><button type='sumbit' class="btn">CONFIRM</button></center>
            
            <br>
        </form>
        
    </div>
    
        <!-- <button class="btn"><i class="fas fa-chalkboard-teacher"></i> &nbsp;Create an Account</button></a>&nbsp;&nbsp; -->
    </div>
    <br>
    <p style="font-size: 10pt; font-weight: 600;">For New User</p>
    <hr>
        <a href="{% url 'main:signup' 'teacher' %}">
        <button type='sumbit' style="background-color:rgb(12, 129, 2); border-radius: 5px; color: white"><i class="fas fa-user-plus"></i> Create an Account</button></a>
    
       
</center> 

{% endblock %}