OnlineTestApplication/OnlineTestApplication/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('teacher/',include('teacher.urls')),
    path('student/',include('student.urls')),
    path('onlinetest/',include('onlinetest.urls')),
     path('password_change/', views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
         path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

OnlineTestApplication/main/urls.py
from django.urls import path
from .views import *
app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('signup/<str:category>/', signup, name='signup'),
    path('teachersignin/',teacher_signin,name='teacher_signin'),
    path('studentsignin/',student_signin,name='student_signin'),
    path('signout/', signout, name='signout'),

]

OnlineTestApplication/onlinetest/urls.py
from django.urls import path

from .views import *
app_name = 'onlinetest'


urlpatterns = [
        path('coursesubjectview/',course_subject_view,name='course_subject_view'),
        path('courselist/',course_list,name='course_list'),
        path('courseupdate/<int:id>',course_update,name='course_update'),
        path('addnewcourse/',add_new_course,name='add_new_course'),
        
        path('subjectlist/',subject_list,name='subject_list'),
        path('subjectupdate/<int:id>',subject_update,name='subject_update'),
        path('subjectdelete/<int:id>/',subject_delete, name='subject_delete'),
        path('addnewsubject/',add_new_subject,name='add_new_subject'),

        path('questionview/',question_view,name='question_view'),
        path('questionlist/',question_list,name='question_list'),
        path('questionupdate/<int:id>',question_update,name='question_update'),
        path('questiondelete/<int:id>/',question_delete, name='question_delete'),
        path('addnewquestion/',add_new_question,name='add_new_question'),
]

OnlineTestApplication/teacher/urls.py
from django.urls import path

from .views import *
app_name = 'teacher'


urlpatterns = [
        # path('',teacher,name='teacher'),
        path('profile/',teacher_profile,name='profile'),
        path('edit/<int:id>/', edit_teacher, name='edit_teacher'),
        path('checkstudentperformance/',check_student_performance,name="check_student_performance"),
]

OnlineTestApplication/teacher/models.py
from django.db import models
from OnlineTestApplication import settings
# Create your models here.
User = settings.AUTH_USER_MODEL

class Teacher(models.Model):
    full_name = models.CharField(max_length=50,null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_photo = models.ImageField(upload_to='teacher/profile/', null=True, blank=True)
    address = models.CharField(max_length=80,null=True, blank=True)
    contactno = models.PositiveIntegerField(null=True, blank=True)
    def __str__(self):
        return str(self.id)

OnlineTestApplication/teacher/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, User
from .models import Teacher


class TeacherForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your Full Name'}),label='Full Name')
    dob = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control','placeholder':'YYYY-MM-DD'}),label='Date of Birth')
    profile_photo = forms.ImageField()
    address = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Enter your Address'}),label='Address')
    contactno = forms.IntegerField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Contact No.'}),label='Contact No.')
    class Meta:
        model = Teacher
        fields = ['full_name','dob', 'profile_photo','address', 'contactno']

OnlineTestApplication/teacher/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import *
from django.contrib import messages
from .models import Teacher
from onlinetest.models import *
from django.contrib.auth.decorators import user_passes_test

# Create your views here.

@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def teacher_profile(request):
    dashboard = 'active'
    teach = Teacher.objects.filter(user=request.user).first()  
    return render(request, 'teacher/teacher_profile.html', locals())    

@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def edit_teacher(request, id):
    dashboard = 'active'
    teach = Teacher.objects.filter(user=request.user).first()  
    object_ = Teacher.objects.filter(id=id).first()
    form = TeacherForm(instance=object_)
    if request.method == 'POST':
        form = TeacherForm(request.POST, request.FILES,
                          instance=object_)
        if form.is_valid():
            form.save()
            messages.success(request, "Object Updated Successfully")
            return redirect('teacher:profile')
        else:
            messages.error(request, "Please Provide valid data")

    return render(request, 'teacher/teacherprofile_update.html', locals())

@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def check_student_performance(request):
    perfomance = 'active'
    teach = Teacher.objects.filter(user=request.user).first()
    stu_perf = Performance.objects.all()
    return render(request, 'teacher/check_student_performance.html', locals())

OnlineTestApplication/templates/teacher/check_student_performance.html
{% extends 'teacher/teacher_base.html' %}
{% load static %}

{% block css %}
      <link rel="stylesheet" href="{% static 'teacher/css/teacher_base.css' %}">
    {% endblock css %}

{% block content %}
<br>
<div style="text-align: center; color: chocolate;">
    <h1 style="text-decoration: underline;">Performance Table</h1>
</div>
<br>
<table class="table table-striped table-hover table-condensed table-bordered table-light text-center">
    <thead class="thead thead-dark">
        <tr scope="col">
            <th>SL.NO.</th>
            <th>Student</th>
            <th>Subject</th>
            <th>Obtained Marks</th>
        </tr>
    </thead>
    <tbody>
        {% for stu in stu_perf %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{stu.student.full_name}}</td>
            <td>{{stu.subject_name|upper}}</td>
            <td>{{stu.obtained_mark}}/{{stu.total_marks}}</td>
        </tr>
        {% endfor %}
    </tbody>

{% endblock %}

OnlineTestApplication/templates/teacher/teacher_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Teacher's Dashboard{% endblock title %}</title>
     <!-- Bootstrap CSS -->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
     integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block css %}
      <link rel="stylesheet" href="{% static 'teacher/css/teacher_base.css' %}">
    {% endblock css %}
    
      
</head>

<body>
    <div class="container-fluid bg-light ">
        <div class="row">
            <div class="col-sm-2">
                <div class="border-right border-primary h-100">
                 <div class="text-center">
                    {% if teach.profile_photo %}
                        <img src='{{teach.profile_photo.url}}' alt="Profile Picture"  class="img-fluid rounded-circle mt-5" width="130px" height="130px">
                    {% else %}
                        No Image Found
                    {% endif %}
                  <h3 class="mt-3">{{user.username}}</h3>
                 </div> 
                 <hr class="border-primary">  
                 <nav class="nav flex-column text-center">
                    <a href="{% url 'teacher:profile' %}" class="nav-link {{dashboard}}">Dashboard</a>
                    <a href="{% url 'onlinetest:course_subject_view' %}" class="nav-link {{course}}">Course & Subject</a>
                    <a href="{% url 'onlinetest:question_view' %}" class="nav-link {{ques}}">Questions</a>
                    <a href="{% url 'teacher:check_student_performance' %}" class="nav-link {{perfomance}}" style="line-height: 20px;">Student's Performance</a>
                    <a href="{% url 'main:signout' %}" class="nav-link">Logout</a>
                 </nav>
                </div>
            </div>   
            <div class="col-sm-10">
                {% block content %}

                {% endblock %}
            </div>   
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-auto-replace-svg="nest"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
</body>
</html>

OnlineTestApplication/templates/teacher/teacher_profile.html
{% extends 'teacher/teacher_base.html' %}
{% load static %}

{% block css %}
      <link rel="stylesheet" href="{% static 'teacher/css/teacher_base.css' %}">
    {% endblock css %}

{% block content %}
<div class="heading1">
<h1>{{user.username}}'s Profile</h1>
</div>


<div class="detailinfo">
    <div class="left">
        <p>
            <span class="info">User Id:</span> <span class="detail">{{user.id}}</span>
        </p>
        <p>
            <span class="info">User Name:</span> <span class="detail">{{user.username}}</span>
        </p>
        <p>
            <span class="info">
                Profile Photo:</span>
            <span>
                {% if teach.profile_photo %}
                    <img src='{{teach.profile_photo.url}}' height=50 width=50 style="border-radius: 30px;">
                {% else %}
                    No Image Found
                {% endif %}
            </span>
        </p>
        <p>
            <span class="info">Full Name:</span> <span class="detail">{{teach.full_name|capfirst}}</span>
        </p>
        <p>
            <span class="info">Date of Birth:</span> <span class="detail">{{teach.dob}}</span>
        </p>
        <p>
            <span class="info">Email:</span> <span class="detail">{{user.email}}</span>
        </p>
        <p>
            <span class="info">Address:</span> <span class="detail">{{teach.address}}</span>
        </p>
        <p>
            <span class="info">Contact Number:</span> <span class="detail">{{teach.contactno}}</span>
        </p>
       
    </div>
</div>

<div class="text-center">
    <a class="btn btn-success btn-sm m-2" href="{% url 'teacher:edit_teacher' teach.id %}"> <i class="fas fa-edit ml-1"></i> Update</a>
</div>
{% endblock %}

OnlineTestApplication/templates/teacher/teacherprofile_update.html
{% extends 'teacher/teacher_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block css %}
      <link rel="stylesheet" href="{% static 'teacher/css/teacher_base.css' %}">
    {% endblock css %}

{% block content %}
<div class="heading1">
    <h1>{{user.username|capfirst}}'s Profile</h1>
</div>

<center> 
    <div style=" width: 50%; border: 10px outset rgb(28, 176, 196); border-radius: 60px;">
    
        
    <div style="background: linear-gradient(to bottom, #ccffff 0%, #5f98ee 100%);  border-radius: 50px;">
        <br>
        <form method="POST"  style="text-align: center;" enctype="multipart/form-data">
                       
        {% csrf_token %}
     
            {{form.full_name|as_crispy_field}}<br>
        
            {{form.dob|as_crispy_field}}<br>

            {{form.profile_photo|as_crispy_field}}<br>
       
            {{form.address|as_crispy_field}}<br>
       
            {{form.contactno|as_crispy_field}}<br>
    
            <br><center><button type='sumbit' class="btn btn-success btn-sm m-2">CONFIRM</button></center>
            <br><br>
        </form>
    </div>
    </div>
</center> 


{% endblock %}