OnlineTestApplication/OnlineTestApplication/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('teacher/',include('teacher.urls')),
    path('student/',include('student.urls')),
    path('onlinetest/',include('onlinetest.urls')),
     path('password_change/', views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
         path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

OnlineTestApplication/main/urls.py
from django.urls import path
from .views import *
app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('signup/<str:category>/', signup, name='signup'),
    path('teachersignin/',teacher_signin,name='teacher_signin'),
    path('studentsignin/',student_signin,name='student_signin'),
    path('signout/', signout, name='signout'),

]

OnlineTestApplication/onlinetest/urls.py
from django.urls import path

from .views import *
app_name = 'onlinetest'


urlpatterns = [
        path('coursesubjectview/',course_subject_view,name='course_subject_view'),
        path('courselist/',course_list,name='course_list'),
        path('courseupdate/<int:id>',course_update,name='course_update'),
        path('addnewcourse/',add_new_course,name='add_new_course'),
        
        path('subjectlist/',subject_list,name='subject_list'),
        path('subjectupdate/<int:id>',subject_update,name='subject_update'),
        path('subjectdelete/<int:id>/',subject_delete, name='subject_delete'),
        path('addnewsubject/',add_new_subject,name='add_new_subject'),

        path('questionview/',question_view,name='question_view'),
        path('questionlist/',question_list,name='question_list'),
        path('questionupdate/<int:id>',question_update,name='question_update'),
        path('questiondelete/<int:id>/',question_delete, name='question_delete'),
        path('addnewquestion/',add_new_question,name='add_new_question'),
]

OnlineTestApplication/onlinetest/models.py
from django.db import models
from student.models import *

# Create your models here.
class Course(models.Model):
    course_name = models.CharField(max_length=30)
    def __str__(self):
        return self.course_name

class Subject(models.Model):
    course_name = models.ForeignKey(Course, on_delete=models.CASCADE)
    subject_name = models.CharField(max_length=30)
    total_marks = models.PositiveIntegerField()
    def __str__(self):
        return self.subject_name

options = [
    ('option1','option1'),
    ('option2','option2'),
    ('option3','option3'),
    ('option4','option4')]
class Question(models.Model):
    subject_name = models.ForeignKey(Subject, on_delete=models.CASCADE)
    question = models.TextField()
    option1 = models.CharField(max_length=100)
    option2 = models.CharField(max_length=100)
    option3 = models.CharField(max_length=100)
    option4 = models.CharField(max_length=100)
    correct_option = models.CharField(choices=options,max_length=100)
    ques_mark = models.PositiveIntegerField()

class Performance(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject_name = models.ForeignKey(Subject, on_delete=models.CASCADE)
    obtained_mark = models.IntegerField()
    total_marks = models.PositiveIntegerField()

OnlineTestApplication/onlinetest/forms.py
from django import forms
from .models import *


class CourseForm(forms.ModelForm):
    course_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Add new course'}),label='Add New Course')
    class Meta:
        model = Course
        fields = "__all__"

class SubjectForm(forms.ModelForm):
    # course_name = forms.Select(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Select course'}),label='Course')
    subject_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Add new subject'}),label='Add New Subject')
    total_marks = forms.IntegerField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter total marks'}),label='Total marks')
    class Meta:
        model = Subject
        fields = "__all__"
        widgets = {
            'course_name': forms.Select(attrs={'class': 'custom-select'}),
        }
        labels = {
            'course_name': 'Course',
        }

class QuestionForm(forms.ModelForm):
    # subject_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Select Subject'}),label='Subject')
    question = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'put question here'}),label='Question')
    option1 = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'First option'}),label='Option 1')
    option2 = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'second option'}),label='Option 2')
    option3 = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'third option'}),label='Option 3')
    option4 = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'fourth option'}),label='Option 4')
    ques_mark = forms.IntegerField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'mark for this question'}),label='Mark for this question')
    class Meta:
        model = Question
        fields = "__all__"
        widgets = {
            'subject_name': forms.Select(attrs={'class': 'custom-select'}),
            'correct_option': forms.Select(attrs={'class': 'custom-select'}),
        }
        labels = {
            'subject_name': 'Subject',
            'correct_option': 'Correct Option',
        }

OnlineTestApplication/onlinetest/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from teacher.models import Teacher
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
# Create your views here.


@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def course_subject_view(request):
    course = "active"
    teach = Teacher.objects.filter(user=request.user).first() 
    return render(request, 'onlinetest/course_subject_view.html',locals())

# Related to Courses
@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def course_list(request):
    course = "active"
    teach = Teacher.objects.filter(user=request.user).first() 
    courselist = Course.objects.all()
    return render(request, 'onlinetest/course_list.html', locals())

@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def course_update(request, id):
    course = "active"
    teach = Teacher.objects.filter(user=request.user).first()
    object_ = Course.objects.filter(id=id).first()
    form = CourseForm(instance=object_)
    if request.method == 'POST':
        form = CourseForm(request.POST, instance=object_)
        if form.is_valid():
            form.save()
            messages.success(request, "Course Updated Successfully")
            return redirect('onlinetest:course_list')
        else:
            messages.error(request, "Please Provide valid data")
    return render(request, 'onlinetest/course_update.html', locals())

@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def add_new_course(request):
    course = "active"
    teach = Teacher.objects.filter(user=request.user).first()
    form = CourseForm()
    if request.method=='POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"CONFIRMED !!!!")
            return redirect('onlinetest:course_subject_view')
    return render(request, 'onlinetest/add_new_course.html', locals())

# Related to Subjects
@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def subject_list(request):
    course = "active"
    teach = Teacher.objects.filter(user=request.user).first() 
    subjectlist = Subject.objects.all()
    return render(request, 'onlinetest/subject_list.html', locals())

@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def subject_update(request, id):
    course = "active"
    teach = Teacher.objects.filter(user=request.user).first()
    object_ = Subject.objects.filter(id=id).first()
    form = SubjectForm(instance=object_)
    if request.method == 'POST':
        form = SubjectForm(request.POST, instance=object_)
        if form.is_valid():
            form.save()
            messages.success(request, "Subject Updated Successfully")
            return redirect('onlinetest:subject_list')
        else:
            messages.error(request, "Please Provide valid data")
    return render(request, 'onlinetest/subject_update.html', locals())

@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def subject_delete(request, id):
    Subject.objects.filter(id=id).first().delete()
    return redirect('onlinetest:subject_list')

@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def add_new_subject(request):
    course = "active"
    teach = Teacher.objects.filter(user=request.user).first()
    form = SubjectForm()
    if request.method=='POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"CONFIRMED !!!!")
            return redirect('onlinetest:course_subject_view')
    return render(request, 'onlinetest/add_new_subject.html', locals())

@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def question_view(request):
    ques = "active"
    teach = Teacher.objects.filter(user=request.user).first() 
    return render(request, 'onlinetest/question_view.html',locals())

@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def question_list(request):
    ques = "active"
    teach = Teacher.objects.filter(user=request.user).first() 
    questionlist = Question.objects.all()
    return render(request, 'onlinetest/question_list.html', locals())

@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def question_update(request, id):
    ques = "active"
    teach = Teacher.objects.filter(user=request.user).first()
    object_ = Question.objects.filter(id=id).first()
    form = QuestionForm(instance=object_)
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=object_)
        if form.is_valid():
            form.save()
            messages.success(request, "Subject Updated Successfully")
            return redirect('onlinetest:question_list')
        else:
            messages.error(request, "Please Provide valid data")
    return render(request, 'onlinetest/question_update.html', locals())

@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def question_delete(request, id):
    Question.objects.filter(id=id).first().delete()
    return redirect('onlinetest:question_list')

@user_passes_test(lambda u: u.is_teacher and u.is_verified)
def add_new_question(request):
    ques = "active"
    teach = Teacher.objects.filter(user=request.user).first()
    form = QuestionForm()
    if request.method=='POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"CONFIRMED !!!!")
            return redirect('onlinetest:question_view')
    return render(request, 'onlinetest/add_new_question.html', locals())

OnlineTestApplication/templates/onlinetest/add_new_course.html
{% extends 'teacher/teacher_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Course & Subject{% endblock title %}


{% block content %}
<center> 
    
    <div style=" width: 80%; border: 10px outset rgb(168, 170, 168); border-radius: 10px; margin: 100px;">
        
    <div style="background: linear-gradient(to bottom, #fffccc 0%, #32f3a3 100%);  border-radius: 0px;">
        
        <h1> Add New Course</h1>
        <br>
        <form method="POST"  style="text-align: center;">
                       
        {% csrf_token %}
     
            {{form.course_name|as_crispy_field}}<br>
    
            <br><center><button type='sumbit' class="btn btn-success btn-sm m-2">CONFIRM</button></center>
            <br><br>
        </form>
    </div>
    </div>
</center> 


{% endblock content %}

OnlineTestApplication/templates/onlinetest/add_new_question.html
{% extends 'teacher/teacher_base.html' %}


{% block title %}Questions{% endblock title %}


{% block content %}
<center> 
    
    <div style=" width: 80%; border: 10px outset rgb(168, 170, 168); border-radius: 10px; margin: 100px;">
        
    <div style="background: linear-gradient(to bottom, #fffccc 0%, #cfcfcf 100%);  border-radius: 0px;">
        
        <h1> Add New Question</h1>
        <br>
        <form method="POST"  style="text-align: center;">
                       
        {% csrf_token %}
     
            {{form}}<br>
    
            <br><center><button type='sumbit' class="btn btn-success btn-sm m-2">CONFIRM</button></center>
            <br><br>
        </form>
    </div>
    </div>
</center> 


{% endblock content %}

OnlineTestApplication/templates/onlinetest/add_new_subject.html
{% extends 'teacher/teacher_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Course & Subject{% endblock title %}


{% block content %}
<center> 
    
    <div style=" width: 80%; border: 10px outset rgb(168, 170, 168); border-radius: 10px; margin: 100px;">
        
    <div style="background: linear-gradient(to bottom, #fffccc 0%, #32f3a3 100%);  border-radius: 0px;">
        
        <h1> Add New Subject</h1>
        <br>
        <form method="POST"  style="text-align: center;">
                       
        {% csrf_token %}
     
            {{form.course_name|as_crispy_field}}<br>
            {{form.subject_name|as_crispy_field}}<br>
            {{form.total_marks|as_crispy_field}}<br>
            <br><center><button type='sumbit' class="btn btn-success btn-sm m-2">CONFIRM</button></center>
            <br><br>
        </form>
    </div>
    </div>
</center> 


{% endblock content %}

OnlineTestApplication/templates/onlinetest/course_list.html
{% extends 'teacher/teacher_base.html' %}


{% block title %}Course & Subject{% endblock title %}


{% block content %}

<table class="table table-striped table-hover table-condensed table-bordered table-light text-center">
    <thead class="thead thead-dark">
        <tr>
            <th scope="col">SL.NO.</th>
            <th scope="col">Course Name</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>

        {% for cl in courselist %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{cl.course_name|upper}}</td>
            <td>
                 <a class="btn btn-warning btn-sm m-2" href="{% url 'onlinetest:course_update' cl.id %}"> <i class="fas fa-edit ml-1"></i> Update</a>
                <!-- <a class="btn btn-danger btn-sm m-2" href=""> <i class="fas fa-trash-alt ml-1"></i> Delete</a> -->

            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock content %}

OnlineTestApplication/templates/onlinetest/course_subject_view.html
{% extends 'teacher/teacher_base.html' %}

{% block title %}Course & Subject{% endblock title %}

{% block css %}
{{block.super}}
<style>
    .div1{
        padding: 20px;
        margin: 50px;
    }
    h1{
        color: rgb(78, 4, 121);
    }
    .btn{
        padding: 20px;
        font-size: 15pt;
    }
    .btn:hover{
            text-decoration: underline;
    }
    .div1 a {
        color: white; 
        font-size: 15pt;
    }

</style>

{% endblock css %}


{% block content %}
<div class="div1">
<h1>Courses</h1>
<hr class="border-primary">
<div class="row">   
    <div class="col-sm-6">  

        <a href="{% url 'onlinetest:course_list' %}"><button type='sumbit' class="btn btn-primary btn-sm m-2">View Courses</button></a>
    </div>
    <div class="col-sm-6">  
        <a href="{% url 'onlinetest:add_new_course' %}"><button type='sumbit' class="btn btn-primary btn-sm m-2">Add new Course</button></a>
        
    </div>
</div>
<br><br>
<br><br>
<h1>Subjects</h1>
<hr class="border-primary">
<div class="row">
    <div class="col-sm-6">  
        <a href="{% url 'onlinetest:subject_list' %}"><button type='sumbit' class="btn btn-primary btn-sm m-2">View Subjects</button></a>
        
    </div>
    <div class="col-sm-6">  
        <a href="{% url 'onlinetest:add_new_subject' %}"><button type='sumbit' class="btn btn-primary btn-sm m-2">Add new Subject</button></a>
        
    </div>
</div>
</div>
{% endblock %}

OnlineTestApplication/templates/onlinetest/course_update.html
{% extends 'teacher/teacher_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Course & Subject{% endblock title %}


{% block content %}
<center> 
    
    <div style=" width: 80%; border: 10px outset rgb(168, 170, 168); border-radius: 10px; margin: 100px;">
       
        
    <div style="background: linear-gradient(to bottom, #fffccc 0%, #32f3a3 100%);  border-radius: 0px;">
        
        <h1> Update Course</h1>
        <br>
        <form method="POST"  style="text-align: center;">
                       
        {% csrf_token %}
     
            {{form.course_name|as_crispy_field}}<br>
    
            <br><center><button type='sumbit' class="btn btn-success btn-sm m-2">CONFIRM</button></center>
            <br><br>
        </form>
    </div>
    </div>
</center> 


{% endblock content %}

OnlineTestApplication/templates/onlinetest/question_list.html
{% extends 'teacher/teacher_base.html' %}


{% block title %}Questions{% endblock title %}


{% block content %}
<h1 style="text-align: center;">Questions List</h1>
<table class="table table-striped table-hover table-condensed table-bordered table-light text-center">
    <thead class="thead thead-dark">
        <tr scope="col">
            <th>SL.NO.</th>
            <th>Subject Name</th>
            <th>Question</th>
            <th>Option1</th>
            <th>Option2</th>
            <th>Option3</th>
            <th>Option4</th>
            <th>Correct Option</th>
            <th>Mark</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>

        {% for ql in questionlist %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{ql.subject_name}}</td>
            <td>{{ql.question}}</td>
            <td>{{ql.option1}}</td>
            <td>{{ql.option2}}</td>
            <td>{{ql.option3}}</td>
            <td>{{ql.option4}}</td>
            <td>{{ql.correct_option}}</td>
            <td>{{ql.ques_mark}}</td>
            <td>
                <a class="btn btn-success btn-sm m-2" href="{% url 'onlinetest:question_update' ql.id %}"> <i class="fas fa-edit ml-1"></i> Update</a>
                
                 <!-- Button trigger modal -->
                 <button type="button" class="btn btn-danger btn-sm m-2" data-bs-toggle="modal" data-bs-target="#exampleModal{{ql.id}}">
                    <i class="fas fa-trash-alt ml-1"></i> Delete
                </button>
  
                <!-- Modal -->
                <div class="modal fade" id="exampleModal{{ql.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Are you sure want to delete this Question: </h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                       <h5 style="color: brown;">{{ql.question}}</h5>
                      </div>
                      <div class="modal-footer">
                        <a class="btn btn-danger btn-sm m-2" href="{% url 'onlinetest:question_delete' ql.id %}"> <i class="fas fa-trash-alt ml-1"></i> Delete</a>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock content %}

OnlineTestApplication/templates/onlinetest/question_update.html
{% extends 'teacher/teacher_base.html' %}


{% block title %}Questions{% endblock title %}


{% block content %}
<center> 
    
    <div style=" width: 80%; border: 10px outset rgb(168, 170, 168); border-radius: 10px; margin: 100px;">
       
        
    <div style="background: linear-gradient(to bottom, #fffccc 0%, #d8d8d7 100%);  border-radius: 0px;">
        
        <h1> Update Question</h1>
        <br>
        <form method="POST"  style="text-align: center;">
                       
        {% csrf_token %}
     
            {{form}}<br>
    
            <br><center><button type='sumbit' class="btn btn-success btn-sm m-2">CONFIRM</button></center>
            <br><br>
        </form>
    </div>
    </div>
</center> 


{% endblock content %}

OnlineTestApplication/templates/onlinetest/question_view.html
{% extends 'teacher/teacher_base.html' %}

{% block title %}Questions{% endblock title %}

{% block css %}
{{block.super}}
<style>
    .div1{
        padding: 20px;
        margin: 50px;
    }
    h1{
        color: rgb(78, 4, 121);
    }
    .btn{
        padding: 20px;
        font-size: 15pt;
    }
    .btn:hover{
            text-decoration: underline;
    }
    .div1 a {
        color: white; 
        font-size: 15pt;
    }

</style>

{% endblock css %}


{% block content %}
<div class="div1">
<h1>Questions</h1>
<hr class="border-primary">
<div class="row">   
    <div class="col-sm-6">  

        <a href="{% url 'onlinetest:question_list' %}"><button type='sumbit' class="btn btn-primary btn-sm m-2">View questions</button></a>
    </div>
    <div class="col-sm-6">  
        <a href="{% url 'onlinetest:add_new_question' %}"><button type='sumbit' class="btn btn-primary btn-sm m-2">Add new questions</button></a>
        
    </div>
</div>

</div>
{% endblock %}

OnlineTestApplication/templates/onlinetest/subject_list.html
{% extends 'teacher/teacher_base.html' %}


{% block title %}Course & Subject{% endblock title %}


{% block content %}

<h1 style="text-align: center;">Subject List</h1>
<table class="table table-striped table-hover table-condensed table-bordered table-light text-center">
    <thead class="thead thead-dark">
        <tr scope="col">
            <th>SL.NO.</th>
            <th>Course Name</th>
            <th>Subject Name</th>
            <th>Total Marks</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>

        {% for sl in subjectlist %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{sl.course_name|upper}}</td>
            <td>{{sl.subject_name}}</td>
            <td>{{sl.total_marks}}</td>
            <td>
                <a class="btn btn-success btn-sm m-2" href="{% url 'onlinetest:subject_update' sl.id %}"> <i class="fas fa-edit ml-1"></i> Update</a>
               
               <!-- Button trigger modal -->
                <button type="button" class="btn btn-danger btn-sm m-2" data-bs-toggle="modal" data-bs-target="#exampleModal{{sl.id}}">
                    <i class="fas fa-trash-alt ml-1"></i> Delete
                </button>
  
                <!-- Modal -->
                <div class="modal fade" id="exampleModal{{sl.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete {{sl.subject_name}}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                       <h5 style="color: red;">Are you sure want to delete Subject: {{sl.subject_name}}</h5>
                      </div>
                      <div class="modal-footer">
                        <a class="btn btn-danger btn-sm m-2" href="{% url 'onlinetest:subject_delete' sl.id %}"> <i class="fas fa-trash-alt ml-1"></i> Delete</a>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>

           </td>
        </tr>
        {% endfor %}
    </tbody>
</table> 



{% endblock content %}

OnlineTestApplication/templates/onlinetest/subject_update.html
{% extends 'teacher/teacher_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Course & Subject{% endblock title %}


{% block content %}
<center> 
    
    <div style=" width: 80%; border: 10px outset rgb(168, 170, 168); border-radius: 10px; margin: 100px;">
       
        
    <div style="background: linear-gradient(to bottom, #fffccc 0%, #b2b6b6 100%);  border-radius: 0px;">
        
        <h1> Update Subject</h1>
        <br>
        <form method="POST"  style="text-align: center;">
                       
        {% csrf_token %}
     
            {{form.course_name|as_crispy_field}}<br>
            {{form.subject_name|as_crispy_field}}<br>
            {{form.total_marks|as_crispy_field}}<br>
    
            <br><center><button type='sumbit' class="btn btn-success btn-sm m-2">CONFIRM</button></center>
            <br><br>
        </form>
    </div>
    </div>
</center> 


{% endblock content %}